# Generated by Django 5.1.7 on 2025-07-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='createad_at',
            new_name='created_at',
        ),
    ]
