# Generated by Django 5.1.7 on 2025-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
